data_dim: 6  # number of aligned features (adjust if needed)
latent_dim: 8
j: 1
emb_time_dim: &time 32
mask_emb_dim: &mask 8
use_observation_mask: false
static_embed_dim: &static 4 # total side dimension will be 8 * 3 (3 static feats) * hidden dims.
num_classes_per_static: [2, 1, 6]  # [city, station, measurement] 
covariate_dim: &cov 3 # we have 3 covariates (time, )

hidden_dim: &hid 32
channels: &chan 8

hyperparams:
  batch_size: 128
  grad_accum_steps: 1
  lambda_schedule: "linear"
  lambda_start: 0.001
  lambda_end: 1.0
  lambda_warmup_steps: 500
  enc_lr: 5e-4
  dec_lr: 5e-4
  zinit_lr: 5e-4
  trans_lr: 5e-4
  S: 1
  logvar_min: -7.0
  logvar_max: 7.0

encoder:
  fut_mask_emb_dim: *mask
  pad_mask_emb_dim: *mask
  hidden_dim: *hid
  summary_config:
    summary_dim: 32
    num_layers: 2
    time:
      type: "gru"
      hidden_dim: 128
  context:
    channels: *chan
    num_layers: 2
    time:
      type: "conv"
      kernel_size: 2
    feature:
      type: "transformer"
      nheads: 4
      layers: 2
  gaussian_head:
    init_logvar: 0.0
    var_min: 1e-6
    clamp_logvar_max: 6.0
    clamp_logvar_min: -10.0
  latent_init_head:
    init_logvar: 0.0
    var_min: 1e-6
    clamp_logvar_max: 6.0
    clamp_logvar_min: -10.0

decoder:
  mask_emb_dim: *mask
  hidden_dim: *hid
  context:
    channels: *chan
    num_layers: 2
    time:
      type: "conv"
      kernel_size: 2
    feature:
      type: "transformer"
      nheads: 4
      layers: 2
  gaussian_head:
    init_logvar: 0.0
    var_min: 1e-6
    clamp_logvar_max: 6.0
    clamp_logvar_min: -10.0

z_init:
  pad_mask_emb_dim: *mask
  hidden_dim: *hid
  context:
    channels: *chan
    num_layers: 2
    time:
      type: "conv"
      kernel_size: 2
    feature:
      type: "transformer"
      nheads: 2
      layers: 1
  aux_context:
    channels: *chan
    num_layers: 2
    time:
      type: "conv"
      kernel_size: 2
    feature:
      type: "transformer"
      nheads: 2
      layers: 1
      
  gaussian_head:
    init_logvar: 0.0
    var_min: 1e-6
    clamp_logvar_max: 6.0
    clamp_logvar_min: -10.0
  latent_init_head:
    init_logvar: 0.0
    var_min: 1e-6
    clamp_logvar_max: 6.0
    clamp_logvar_min: -10.0

transition:
  type: "gaussian"
  hidden_dim: *hid
  context:
    channels: *chan
    num_layers: 2
    time:
      type: "conv"
    feature:
      type: "transformer"
      nheads: 4
      layers: 2
      
  gaussian_head:
    init_logvar: 0.0
    var_min: 1e-6
    clamp_logvar_max: 6.0
    clamp_logvar_min: -10.0
