data_dim: 35  # 35 PM2.5 stations
latent_dim: 24
j: 2
emb_time_dim: &time 4
mask_emb_dim: &mask 8
use_observation_mask: false
static_embed_dim: &static 4
num_classes_per_static: [2, 35, 1]  
covariate_dim: &cov 3

hidden_dim: &hid 128
channels: &chan 32 # was at 7266 at 32. This takes to 8654, so we will keep it.

hyperparams:
  batch_size: 16
  grad_accum_steps: 1
  lambda_schedule: "linear"
  lambda_start: 0.001
  lambda_end: 1.0
  lambda_warmup_steps: 500
  enc_lr: 5e-4
  dec_lr: 5e-4
  zinit_lr: 5e-4
  trans_lr: 5e-4
  S: 1
  logvar_min: -7.0
  logvar_max: 7.0

encoder:
  fut_mask_emb_dim: *mask
  pad_mask_emb_dim: *mask
  hidden_dim: *hid
  summary_config:
    summary_dim: 128
    num_layers: 3
    time:
      type: "gru"
      hidden_dim: 128 # 128 to 256 was a 5GB memory increase.
  context:
    channels: *chan
    num_layers: 2
    time:
      type: "conv"
      kernel_size: 2
    feature:
      type: "transformer"
      nheads: 4
      layers: 2
  gaussian_head:
    init_logvar: 0.0
    var_min: 1e-6
    clamp_logvar_max: 6.0
    clamp_logvar_min: -10.0
  latent_init_head:
    init_logvar: 0.0
    var_min: 1e-6
    clamp_logvar_max: 6.0
    clamp_logvar_min: -10.0

decoder:
  mask_emb_dim: *mask
  hidden_dim: *hid
  context:
    channels: *chan
    num_layers: 2
    time:
      type: "conv"
      kernel_size: 2
    feature:
      type: "transformer"
      nheads: 4
      layers: 2
  gaussian_head:
    init_logvar: 0.0
    var_min: 1e-6
    clamp_logvar_max: 6.0
    clamp_logvar_min: -10.0

z_init:
  pad_mask_emb_dim: *mask
  hidden_dim: *hid
  context:
    channels: *chan
    num_layers: 2
    time:
      type: "conv"
      kernel_size: 2
    feature:
      type: "transformer"
      nheads: 2
      layers: 1
  aux_context:
    channels: *chan
    num_layers: 2
    time:
      type: "conv"
      kernel_size: 2
    feature:
      type: "transformer"
      nheads: 2
      layers: 1
      
  gaussian_head:
    init_logvar: 0.0
    var_min: 1e-6
    clamp_logvar_max: 6.0
    clamp_logvar_min: -10.0
  latent_init_head:
    init_logvar: 0.0
    var_min: 1e-6
    clamp_logvar_max: 6.0
    clamp_logvar_min: -10.0

transition:
  type: "gaussian"
  hidden_dim: 128
  context:
    channels: 32   
    num_layers: 4
    time:
      type: "conv"
      kernel_size: 2
    feature:
      type: "transformer"
      nheads: 8
      layers: 2
      
  gaussian_head:
    init_logvar: 0.0
    var_min: 1e-6
    clamp_logvar_max: 6.0
    clamp_logvar_min: -10.0
