"""Central hydra-zen configuration: ZenStore, config groups, and top-level DDSSMConf.

This module provides:
  - A ``ZenStore`` with ``transition`` config group (``gaussian`` / ``diffusion``).
  - A ``DDSSMHyperParamsConf`` dataclass for training hyperparameters.
  - A ``DDSSMConf`` that assembles all sub-module configs into a single
    instantiable configuration (built with hydra-zen ``builds()``).
  - A ``DDSSMTrainerConf`` for trainer construction via hydra-zen ``builds()``.
  - ``build_model(yaml_path)`` – a convenience helper that loads a Hydra YAML
    and returns an instantiable config.

All module-level ``*Conf`` classes are generated by ``builds(ClassName,
populate_full_signature=True)`` which is co-located with each class in its
own file.  This file re-exports them via the ZenStore for use with Hydra
config groups.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, List

from hydra_zen import builds, make_config, ZenStore
from omegaconf import MISSING

# ---------------------------------------------------------------------------
# Per-module configs (imported from co-located builds() calls)
# ---------------------------------------------------------------------------

from .encoder import GaussianEncoderConf, GaussianInitPriorConf
from .decoder import DecoderConf
from .transitions.transitions import GaussianTransitionConf
from .transitions.diffusion import DiffusionTransitionConf
from .futsum import FutureSummaryConfig


# ---------------------------------------------------------------------------
# ZenStore with config groups
# ---------------------------------------------------------------------------

store = ZenStore(name="ddssm")

# transition group: gaussian | diffusion
store(GaussianTransitionConf, group="transition", name="gaussian")
store(DiffusionTransitionConf, group="transition", name="diffusion")


# ---------------------------------------------------------------------------
# Hyperparameters dataclass (mirroring the old DDSSMHyperParams Pydantic model)
# ---------------------------------------------------------------------------

@dataclass
class _REWOConf:
    D0: float = 0.1
    nu: float = 1e-3
    alpha: float = 0.99
    tau1: float = 1.0
    tau2: float = 1.0


@dataclass
class DDSSMHyperParamsConf:
    """Training hyperparameters for DDSSM.

    Mirrors the old ``DDSSMHyperParams`` Pydantic model.
    """
    S: int = 1
    ema_decay: float = 0.999
    weight_decay: float = 1e-2
    batch_size: int = 16
    grad_accum_steps: int = 4
    t_chunk: int = 16
    clip_grad_norm: float | None = None

    lambda_schedule: str = "none"  # "none" | "linear" | "cosine" | "rewo"
    lambda_start: float = 0.001
    lambda_end: float = 1.0
    lambda_warmup_steps: int = 10

    enc_lr: float = 5e-4
    dec_lr: float = 5e-4
    zinit_lr: float = 5e-4
    trans_lr: float = 5e-4

    logvar_min: float = -7.0
    logvar_max: float = 7.0

    rewo: _REWOConf = field(default_factory=_REWOConf)


# ---------------------------------------------------------------------------
# Stages dataclasses (slim versions; full logic lives in stages.py)
# ---------------------------------------------------------------------------

@dataclass
class _StageLrsConf:
    dec_lr: float = 5e-4
    zinit_lr: float = 5e-4
    trans_lr: float = 0.0


@dataclass
class _StageTrainableConf:
    decoder: bool = True
    z_init: bool = True
    transition: bool = False


@dataclass
class _StageSchedulerConf:
    warmup_steps: int = 0
    final_lr_scale: float = 1.0


@dataclass
class _LambdaRampConf:
    end: float | None = 1.0
    delay: int = 0
    steps: int | None = None


@dataclass
class StageSpecConf:
    steps: int = MISSING
    trainable: _StageTrainableConf = field(default_factory=_StageTrainableConf)
    lrs: _StageLrsConf = field(default_factory=_StageLrsConf)
    scheduler: _StageSchedulerConf = field(default_factory=_StageSchedulerConf)
    carry_diff_moments: bool = False
    lambda_ramp: _LambdaRampConf = field(default_factory=_LambdaRampConf)
    log_every: int = 10
    val_every: int = 100
    checkpoint_every: int = 1000


@dataclass
class StagesConf:
    stage_2: StageSpecConf | None = None
    stage_3: StageSpecConf | None = None
    run: List[str] = field(default_factory=lambda: ["stage_1", "stage_2", "stage_3"])


# ---------------------------------------------------------------------------
# Top-level DDSSMConf via builds(DDSSM_base)
# ---------------------------------------------------------------------------

from .dssd import DDSSM_base  # noqa: E402 – circular import avoided by late import

DDSSMConf = builds(
    DDSSM_base,
    # Sub-modules: supply sensible placeholder configs; users override per-run.
    encoder=GaussianEncoderConf(
        data_dim=MISSING,
        latent_dim=MISSING,
        j=MISSING,
        emb_time_dim=MISSING,
        use_mask=True,
    ),
    decoder=DecoderConf(
        latent_dim=MISSING,
        data_dim=MISSING,
        j=MISSING,
        emb_time_dim=MISSING,
    ),
    z_init=GaussianInitPriorConf(
        latent_dim=MISSING,
        j=MISSING,
        emb_time_dim=MISSING,
    ),
    transition=GaussianTransitionConf(
        latent_dim=MISSING,
        j=MISSING,
        emb_time_dim=MISSING,
    ),
    j=MISSING,
    data_dim=MISSING,
    latent_dim=MISSING,
    emb_time_dim=16,
    hyperparams=DDSSMHyperParamsConf(),
    populate_full_signature=False,  # explicit fields only; device is runtime
)

store(DDSSMConf, group="model", name="default")

from .train import DDSSMTrainer  # noqa: E402 – circular import avoided by lazy train import

DDSSMTrainerConf = builds(
    DDSSMTrainer,
    model=MISSING,
    device=MISSING,
    optimizer=None,
    csv_log_path=None,
    tensorboard_dir="runs/ddssm",
    wandb_config=None,
    quiet=False,
    populate_full_signature=False,
)

store(DDSSMTrainerConf, group="trainer", name="default")


# ---------------------------------------------------------------------------
# Convenience helper: load a Hydra YAML and return an instantiable config
# ---------------------------------------------------------------------------

def build_model(yaml_path: str) -> Any:
    """Load a Hydra-compatible YAML and return a DDSSMConf-style config.

    For backward compatibility with scripts that previously called
    ``load_config_from_files``.  The returned object can be passed to
    ``hydra_zen.instantiate(cfg)`` to construct the ``DDSSM_base`` model.

    Args:
        yaml_path: Path to the Hydra YAML configuration file.

    Returns:
        An ``OmegaConf`` DictConfig that can be passed to ``instantiate``.
    """
    from omegaconf import OmegaConf

    with open(yaml_path, "r") as f:
        cfg = OmegaConf.load(f)
    return cfg
